services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"


  kafka:
    image: bitnami/kafka:latest
    hostname: kafka-server  # Ensures consistent DNS
    ports:
      - "9092:9092"  # For external clients (optional)
    environment:
      # KRaft Mode Required Configs
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: "0"  # Must be unique per node
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-server:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      
      # Listener Configuration (Critical!)
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-server:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      
      # Health Check Fix (KRaft Compatibility)
      KAFKA_HEALTH_ENABLED: "true"
      KAFKA_HEALTH_PORT: "8080"  # Alternative health check endpoint
      ALLOW_PLAINTEXT_LISTENER: "yes"
    
    networks:
      - app-tier


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  tile38-leader:
    image: tile38/tile38:1.34.1
    container_name: tile38-leader
    command: >
      /bin/sh -c 'mkdir -p tmp/data &&
                  echo "{\"logconfig\":{\"level\":\"debug\",\"encoding\":\"json\",\"outputPaths\":[\"stdout\"],\"errorOutputPaths\":[\"stderr\"],\"encoderConfig\": {\"messageKey\":\"message\",\"levelKey\":\"level\",\"levelEncoder\":\"lowercase\", \"timeKey\":\"timestamp\",\"timeEncoder\":\"ISO8601\"}}}"> tmp/data/config
                  tile38-server -d tmp/data -vv -p 9851 -l json'
    ports:
      - 9851:9851
    volumes:
      - tile38-data:/tmp/data


  python-backend:
    build: ./python_backend
    working_dir: /backend  # 显式指定与 volume 一致
    volumes:
      - ./python_backend:/backend 
    depends_on:
      - kafka
      - tile38-leader
    environment:
      KAFKA_BROKER: kafka:9092
      TILE38_URL: "http://tile38-leader:9851"


networks:
  app-tier:
    driver: bridge
    
volumes:
  tile38-data:
  kafka_data: 



