services:
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_NODE_ID=1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "kafka:9092"]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 30s

  tile38:
      image: tile38/tile38
      container_name: tile38
      ports:
       - "9851:9851"
      entrypoint: ["tile38-server"]
  app:
    build: ./src
    container_name: app
    depends_on:
      kafka:
        condition: service_healthy
      tile38:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      TILE38_HOST: "tile38"
      TILE38_PORT: "9851"
    ports:
      - "8501:8501"  # Streamlit UI
      - "8000:8000"  # WebSocket API (e.g., FastAPI)
    volumes:
      - ./src:/src
